apiVersion: v1
data:
  keystore.p12: {{ .Values.cassandraKeyStoreSecret.keystore }}
kind: Secret
metadata:
  name: {{ .Values.cassandraKeyStoreSecret.name }}
  namespace: {{ .Values.namespace }}
type: Opaque