apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.clusterrolebinding.metadata.name }}
subjects:
- apiGroup: {{ .Values.clusterrolebinding.roleRef.apiGroup }}
  kind: Group
  name: system:serviceaccounts
roleRef:
  kind: {{ .Values.clusterrolebinding.roleRef.kind }}
  name: {{ .Values.clusterrolebinding.roleRef.name }}
  apiGroup: {{ .Values.clusterrolebinding.roleRef.apiGroup }}
