apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.configmaprolebinding.metadata.name }}
  namespace: {{ .Values.namespace }}
subjects:
- kind: {{ .Values.configmaprolebinding.subjects.kind }}
  name: {{ .Values.configmaprolebinding.subjects.name }}
  namespace: {{ .Values.namespace }}
roleRef:
  kind: {{ .Values.configmaprolebinding.roleRef.kind }}
  name: {{ .Values.configmaprolebinding.roleRef.name }}
  apiGroup: {{ .Values.configmaprolebinding.roleRef.apiGroup }}